language: ruby

rvm:
- 2.6.3

services:
  - postgresql
  - xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rspec spec/features/*.rb

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - npm i -g yarn
  - yarn

script:
  - bundle exec rspec