language: ruby

rvm:
- 2.6.3

dist: xenial

services:
  - postgresql

addons:
  chrome: stable

before_install:
  - "export DISPLAY=:99.0"
  - sleep 3 


before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - npm i -g yarn
  - yarn

script:
  - xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rspec spec/features/*.rb
  - bundle exec rspec spec/controller/*.rb