language: ruby
rvm:
- 2.6.3
install: bundle install
services:
  - postgresql
addons:
  chrome: stable
script:
  - bundle exec rails webpacker:compile RAILS_ENV=test 
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec