language: ruby

rvm:
- 2.6.3

dist: trusty

services:
  - postgresql
  # - xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rspec spec/features/*.rb

addons:
  chrome: stable

before_install:
  -  google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # - "export DISPLAY=:99.0"

  # - sleep 3 # give xvfb some time to start


before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - npm i -g yarn
  - yarn

script:
  # - xvfb-run make test
  - bundle exec rspec